# Generated by Django 5.0.6 on 2024-12-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PRE', 'Preparación'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PRE', max_length=3),
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PRE', 'Preparación'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], max_length=3)),
                ('estado_nuevo', models.CharField(choices=[('PRE', 'Preparación'), ('TRA', 'En tránsito'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], max_length=3)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='core.pedido')),
            ],
        ),
    ]
