# Generated by Django 5.1.4 on 2024-12-05 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historialestadopedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('trabajador', 'Trabajador'), ('administrador', 'Administrador')], max_length=50),
        ),
        migrations.CreateModel(
            name='HistorialCambioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_anterior', models.CharField(max_length=50)),
                ('rol_nuevo', models.CharField(max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_rol', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
