# Generated by Django 5.0.6 on 2024-12-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historialestadopedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestadopedido',
            name='estado_anterior',
            field=models.CharField(choices=[('PRE', 'Preparación'), ('TRA', 'En tránsito/Disponible para retiro'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='historialestadopedido',
            name='estado_nuevo',
            field=models.CharField(choices=[('PRE', 'Preparación'), ('TRA', 'En tránsito/Disponible para retiro'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PRE', 'Preparación'), ('TRA', 'En tránsito/Disponible para retiro'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PRE', max_length=3),
        ),
    ]
