# Generated by Django 5.0.6 on 2024-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido_producto_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
    ]
